### ISSUE TITLE
Second window of Eye of MATE don't get focus

### ISSUE THREAD

**Issue by ghost** [mate-desktop/eom#119]
I'm try open some file in Eye of MATE. Then, without close eom window, I'm try open second file. Eom open second file in second window. But this window don't get focus. I'm can workaround this by adding -n to eom command line. But I'm think eom must work correct out of the box.

**Comment by raveit65** [comment]
damned, my crystal ball is broken :no_good: 
distro?
mate version?
package version?

**Comment by Strelok355** [comment]
Distro: Debian Jessie/Debian Testing/Debian Sid.
Mate version: 1.12.1
package version: 1.12.2-1

**Comment by y7x** [comment]
Can confirm. It happens with .jpg and .png as far as I tested.
When opening images from caja, eom sometimes doesn't focus the image it just opened.
You can easily test this by randomly opening different images and you should notice that certain ones just don't pop up.
Might be caja's fault, because when executing eom from the terminal it consistently focuses the image.

Distro: Linux Mint 17.3
Mate version: 1.12.2
package version: 1.12.2-1+rosa

**Comment by vfscanf** [comment]
I created a pull request which should fix this issue.

**Comment by raveit65** [comment]
merged
https://github.com/mate-desktop/eom/commit/1b65a062fc01e15c4a461463a055b90d8cb3235e

**Comment by monsta** [comment]
Well, it's kind of hackish, but I confirm it fixes the issue here :smile:
