### ISSUE TITLE
EOM crashes when using jemalloc

### ISSUE THREAD

**Issue by xdevelnet** [mate-desktop/eom#209]
#### Expected behaviour

Open images like with usual allocator

#### Actual behaviour

Just segmentation fault in a command line even if you're opening eom without images

#### Steps to reproduce the behaviour

1) Download jemalloc library using package manager
2) Install it by putting an appropriate line to /etc/ld.so.preload

#### MATE general version

1.10.2

#### Package version

1.10.3-1+rafaela

#### Linux Distribution

Linux Mint 17.2 Rafaela

Other programs from mate desktop works just fine. I was trying to execute eom with valgrind but it surprisingly working without issues except very slow performance and enormous number of errors from valgrind itself.

I don't know if you were fixed something that may cause such behavior, but if yes - should I try to manually build eom from this repository and try to use it?

**Comment by lukefromdc** [comment]
MATE 1.10 is very old and no longer supported. Can you test if this issue still exists in MATE 1.20 (the current and soon to be previous release?) .

I have libjemalloc1 installed in Debian Unstable (upstream to Ubuntu and LInuxmint) and do not have and never had this problem, no idea if I had that package back in 2015 when MATE 1.10 was current. Note that I was using GTK3 builds all the way back to MATE 1.10(which supported it experimentally) and we've only supported GTK3 since MATE 1.18 and GTK 3.20 or later since MATE 1.20.

**Comment by xdevelnet** [comment]
Unfortunately I don't want to upgrade to newer OS version and my current version is not delivering new software updates (except security updates).
I'm wondering if I could build it from source code and use it.

By the way, I don't think such crash is really about GTK, because other programs are running fine.

Anyway, thanks for help! <3
Going to close this issue and write if i'll achieve some success.
