### ISSUE TITLE
Single image argument should not load entire folder

### ISSUE THREAD

**Issue by JorgeStolfi** [mate-desktop/eom#313]
#### Expected behaviour

When giving a single image as an argument, eom should display only that image.

#### Actual behaviour

When giving a single image as an argument, eom adds all images in the same folder to the list of images to be shown.

That is bad because

1. it is not expected or standard behavior. Users expect a program to read and process only the given files.
2. it complicates or break scripts. E.g `eom ${images[@]}` will do different things depending on how many files are in that list.
3. The folder may contain large or damaged files that the user does not want displayed.
4. Without that "feature", users who want to browse the whole folder could still say `eom myfolder` or `eom myfolder/*.{png,jpg}` etc.  With that "feature", users who want to see only one image have no way to do it.
5. It makes the code more complex than it would have to be, and thus more difficult for others to maintain and upgrade.

See also https://github.com/mate-desktop/eom/issues/130

#### Steps to reproduce the behaviour

Create a folder "test" and copy two image files into it, say "A.png" and "B.png".  Run "eom test/B.png". The arrows will show both A.png and B.png.

#### MATE general version

1.24.0

#### Package version

1.24.0

#### Linux Distribution

20.04.1-Ubuntu

#### Link to bugreport of your Distribution (requirement)

What is that, and how do I get it?

**Comment by cwendling** [comment]
IMO it is expected in the common use case of opening EOM my double-clicking/pressing <kbd>Enter</kbd> from the file manager. With the current behavior, one can open the first image in the folder and then browse them, which to my knowledge is a *very* common use case.  With the proposed behavior, the only "practical" solution from a file manager would be to select all images first, and then hit <kbd>Enter</kbd>, which seems needlessly complicated.  Also, there would be no easy way to start in the middle of a series while still being able to browser before and after.

If really having EOM allow browsing files not explicitly listed on the CLI is important for some use case, it probably then should be an option to keep the IMO mainstream usage of just opening a file through the file manager and starting browsing.  Or if really important, it could be an option to enable it that would be embedded in the .desktop file so opening through the file manager would do it automatically, either way.

However, why is this a problem?  If it is merely speed, probably EOM should be improved not to be overly impacted by large directories/images (lazier loading or such maybe), as it would benefit all uses cases, including listing a zillion files on the CLI.

> 1. it is not expected or standard behavior. Users expect a program to read and process only the given files.

Well, IMO this is the case for CLI tools, not so much for mostly GUI viewers, which are rather expected to "just work", whatever that might mean.

**Comment by vkareh** [comment]
I think this is a `wontfix` from us. If someone wants to add a specific command line parameter to open a single file without loading the entire directory, maybe that can be reviewed/tested, but sounds unnecessarily complex. You should be using a different program for this use case, not a general purpose image viewer.

**Comment by JosuaRieder** [comment]
I'm running into the same problem and I'm now replacing eom because of this. Starting eom in a directory with many images takes tens of seconds for me.

I've briefly looked at other image viewers and how they behave in this scenario:

https://github.com/derf/feh: Seems to open images in some kind of single-file mode when launched from the terminal whereas the .desktop file launches it in whole-directory mode (`--start-at`). In that mode, it also finishes file gathering before showing a window (eom behavior) but it is about an order of magnitude faster than eom.

https://github.com/easymodo/qimgv: No special flags in .desktop. Does some kind of deferred loading where it shows the image quickly after launching but then takes some time to enable browsing images inside the image viewer. I didn't measure it but for me the delay was faster than the eom startup delay but slower than the feh startup delay.
