### ISSUE TITLE
Eye of Mate drag picture

### ISSUE THREAD

**Issue by thedisbo1125** [mate-desktop/eom#97]
In version 1.10.0, if I enlarge a picture beyond the screen, when I try to drag it to see the bottom, it goes to the top of the picture and doesn't move.  In previous versions, I was able to drag it and see the bottom of the picture.

**Comment by monsta** [comment]
Did you try scrolling it (with either mouse wheel or the scrollbar) instead of dragging? Will the problem appear?

**Comment by direwolfie** [comment]
Have the same issue with v1.10.0 on Linux Mint 17.2 x64. But it happens only with some files.

Here is the examples of the picture - http://www.1iz.net/data/media/58/Hong_Kong_Vertical__700_x_1000.jpg

To reproduce: 
1.Save the image. 
2.Open the EOM window in full-screen. 
3.Press 1 (on keyboard, short cut to view image in full size). This presumes that the image is larger than the screen.
4.Try to scroll.

This is might have been fixed in this patch -  https://github.com/mate-desktop/eom/commit/63eee4d641692a07f41bce3b7fd21668d8fe2f1e (see this issue https://github.com/mate-desktop/eom/issues/98)
But just in case, wrote this up.
